trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'renansald/portfolio'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Docker Image
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: 'dockerHub-sc'
        command: build
        dockerfile: '**/Dockerfile'
        imageName: $(imageName)
        includeLatestTag: true
        useDefaultContext: false
        buildContext: .
    - task: Docker@2
      displayName: Push Docker image
      condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
      inputs:
        containerRegistry: 'dockerHub-sc'
        command: push
        imageName: $(imageName)
        includeLatestTag: true